name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK to GitHub Releases
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app.apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Install Firebase CLI
      run: |
        sudo curl -sL firebase.tools | bash

    - name: Login to Firebase
      run: firebase login:ci --token "$FIREBASE_TOKEN"

    - name: Deploy to Firebase App Distribution
      run: firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk --app "$FIREBASE_APP_ID" --groups "$FIREBASE_GROUP_ID" --token "$FIREBASE_TOKEN"
      
    - name: Deploy to Google Play Store
      uses: r0adkll/google-play-publisher-action@v1
      with:
        service-account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        apk-file-path: app/build/outputs/apk/debug/app-debug.apk
        track: internal
        apk-version-code: ${{ env.GITHUB_RUN_NUMBER }}
        apk-release-notes: "Release ${{ env.GITHUB_RUN_NUMBER }} from GitHub Actions"
