name: Android CI/CD

on:
  push:
    branches:
      - main

env:
  ANDROID_SDK_ROOT: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Setup Android SDK
      uses: actions/setup-android@v1
      with:
        android-sdk-license: accept
        android-sdk: "platform-tools,tools,build-tools;29.0.2"

    - name: Build and test the app
      run: ./gradlew build connectedCheck

    - name: Upload APK to GitHub Releases
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app.apk
        path: app/build/outputs/apk/debug/app-debug.apk
