apiVersion: v1alpha
kind: espresso
defaults: {}
showConsoleLog: false
sauce:
  region: eu-central-1
  concurrency: 2
espresso:
  app: $BITRISE_APK_PATH
  testApp: $BITRISE_TEST_APK_PATH
suites:
- name: Espresso Android UI tests
  emulators:
  - name: Android GoogleAPI Emulator
    platformVersions:
    - "12.0"
  devices:
   - id: Google_Pixel_2_real_us
   - name: "Google Pixel.*"
     platformVersion: "8.1"
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: artifacts
