apiVersion: v1alpha
kind: espresso
defaults: {}
showConsoleLog: false
sauce:
  region: eu-central-1
  concurrency: 2
espresso:
  app: $BITRISE_APK_PATH
  testApp: $BITRISE_TEST_APK_PATH
suites:
- name: Espresso Android UI tests
  emulators:
  - name: Android GoogleAPI Emulator
    platformVersions:
    - "12.0"
  devices:
   - id: Samsung_Galaxy_S9_free
     platformVersion: "10"
artifacts:
  download:
    match:
    - '*'
    when: always
    directory: artifacts
